language: haxe

os:
  - linux

haxe:
  - "3.4.4"
  - development

matrix:
  allow_failures:
    - haxe: development

install:
    - haxelib git chrome-app https://github.com/tong/chrome.app
    - haxelib dev chrome-extension .

script:
  - haxe haxedoc.hxml
