language: haxe

os:
  - linux

haxe:
  - "3.4.7"
  - "4.0.5"
  - development

matrix:
  allow_failures:
    - haxe: "3.4.7"
    - haxe: "development"

install:
    - haxelib git chrome-app https://github.com/tong/chrome.app
    - haxelib dev chrome-extension .

script:
  - haxe haxedoc.hxml
